### ISSUE TITLE
issues without `rg`

### ISSUE THREAD

**Issue by kujohn** [pechorin/any-jump.nvim#1]
I have ag installed but encountered error running with it alone. If I install `rg` it works great.

**Comment by wallace11** [comment]
Seems like the `any_jump_search_prefered_engine` is being overwritten by the plugin, regardless of what's set in vimrc. Manually running `let g:any_jump_search_prefered_engine = 'ag'` seems to work fine.

**Comment by pechorin** [comment]
I will try to remove rg and see how ag-only setup work, thanks

**Comment by wallace11** [comment]
I simply check by running `:echo g:any_jump_search_prefered_engine` and find out that it's returning `rg` regardless of what I set in my vimrc...

**Comment by pechorin** [comment]
@wallace11 @kujohn 

Thanks, issue fixed in https://github.com/pechorin/any-jump.nvim/commit/d436b1b07cfac89c629bf14e676ed911d7c1392b

Please update plugin :)

**Comment by pechorin** [comment]
Also i need to mention what `rg` and `ag` search results are different, so i need to recheck what kind of conditions it is.
