### ISSUE TITLE
"not found map definition for filetype 'cpp'"

### ISSUE THREAD

**Issue by wbthomason** [pechorin/any-jump.nvim#2]
As the title indicates, I get this error while attempting to use the plugin in a C++ file. Looking at the code in `generator/` it appears that you've generated regexes for a possible `c++` filetype, but Neovim uses `cpp` as the filetype for C++ files. This may also be an issue for other languages with a similar difference in language name and filetype name.

**Comment by wookayin** [comment]
Same issue for python. Vim uses `python` but rg expects `--type py` for python files. We should have a hard-coded mapping from vim-filetype names and to rg-filetype names.

**Comment by pechorin** [comment]
Thanks for report, i will fix it with providing language names aliases

**Comment by pechorin** [comment]
@wbthomason cpp fixed :)

**Comment by pechorin** [comment]
@wookayin python also fixed. Please update plugin and try .)

**Comment by pechorin** [comment]
fixed in https://github.com/pechorin/any-jump.nvim/commit/dd466a688a2f321b097d6563244224b41ec3bdfa; please update plugin
