### ISSUE TITLE
Unrecognized filetype javascript

### ISSUE THREAD

**Issue by pixelgrid** [pechorin/any-jump.nvim#7]
Hey, the plugin looks dope!

trying to test the plugin in javascript apps but i get this error
```

Error detected while processing function <SNR>51_Jump[24]..search#SearchDefinitions[19]..<SNR>75_RunRgDefinitionSearch[5]..<SNR>75_ParseRgResults:
line    7:
E474: Unidentified byte: unrecognized file type: javascript
E474: Failed to parse unrecognized file type: javascript
```
any pointers on what might be the issue?

```
:version                                                                                                                             
NVIM v0.5.0-nightly
Build type: Release
LuaJIT 2.0.5
Compilation: /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super/gcc-9 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall
 -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvl
a -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS
_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20191210-22270-yx8i82/build/config -I/tmp/neovim-20191210-22270-yx8i82/src -I/home/linuxbrew/.linuxb
rew/include -I/tmp/neovim-20191210-22270-yx8i82/deps-build/include -I/usr/include -I/tmp/neovim-20191210-22270-yx8i82/build/src/nvim/auto -I/t
mp/neovim-20191210-22270-yx8i82/build/include
```

**Comment by wookayin** [comment]
Related issue: #2

**Comment by pechorin** [comment]
Okay, i will fix it now, this is important part :) (js support in general)

**Comment by wookayin** [comment]
It would be great to have a complete enumeration over all filetypes you auto-generated for.

**Comment by pechorin** [comment]
@pixelgrid fixed in https://github.com/pechorin/any-jump.nvim/commit/455db0b8b2cb3aee5474fdd3fb0dda70d39fb5b3

**Comment by pixelgrid** [comment]
Can confirm it now shows results. Thanks for the quick fix

**Comment by pechorin** [comment]
@wookayin yes, thanks for idea, now i understand what this is important part. I will also try to handle exotic vim filetypes like `es6` / `javascriptreact` (for now plugin will not work for my jsx files with javascriptreact filetype).

**Comment by pixelgrid** [comment]
@pechorin while you implement the mapping on the go maybe you can give the option to have custom mappings through init.vim?

**Comment by pechorin** [comment]
@pixelgrid i think this is nice idea, thank, will include this ability in my implementation.
